### ISSUE TITLE
demos

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE-ACAT-2017#17]
@bazinski can we have a list of demonstrations that we'd like to show ?

Like, trivial submission of ROOT+Pythia8 to generate pp collissions ? I'd like to have something in a script that can be shown to execute...

**Comment by bazinski** [comment]
sorry missed this for some reason, ja working on it.

**Comment by bazinski** [comment]
10 nodes up with correct cvmfs 10-34 (and 5 unhappy)... finally.
480 cores

**Comment by brucellino** [comment]
woot ? Can we have some sort of proof  ?

**Comment by bazinski** [comment]
root@grid-ce:~ $ pdsh -w gnode-2-[10-34].chpc.ac.za "cat /cvmfs/code-rade.africa-grid.org/version " | sort
gnode-2-34: ssh_exchange_identification: Connection closed by remote host
pdsh@grid-ce: gnode-2-34: ssh exited with exit code 255
gnode-2-20: ssh: connect to host gnode-2-20.chpc.ac.za port 22: No route to host
pdsh@grid-ce: gnode-2-20: ssh exited with exit code 255
gnode-2-21: ssh: connect to host gnode-2-21.chpc.ac.za port 22: No route to host
pdsh@grid-ce: gnode-2-21: ssh exited with exit code 255
gnode-2-28: ssh: connect to host gnode-2-28.chpc.ac.za port 22: No route to host
pdsh@grid-ce: gnode-2-28: ssh exited with exit code 255
gnode-2-29: ssh: connect to host gnode-2-29.chpc.ac.za port 22: No route to host
pdsh@grid-ce: gnode-2-29: ssh exited with exit code 255
gnode-2-10: FR3 Build 298 triggered by scotch
gnode-2-11: FR3 Build 298 triggered by scotch
gnode-2-12: FR3 Build 298 triggered by scotch
gnode-2-13: FR3 Build 298 triggered by scotch
gnode-2-14: FR3 Build 298 triggered by scotch
gnode-2-15: FR3 Build 298 triggered by scotch
gnode-2-16: FR3 Build 298 triggered by scotch
gnode-2-17: FR3 Build 298 triggered by scotch
gnode-2-18: FR3 Build 298 triggered by scotch
gnode-2-19: FR3 Build 298 triggered by scotch
gnode-2-22: FR3 Build 298 triggered by scotch
gnode-2-23: FR3 Build 298 triggered by scotch
gnode-2-24: FR3 Build 298 triggered by scotch
gnode-2-25: FR3 Build 298 triggered by scotch
gnode-2-26: FR3 Build 298 triggered by scotch
gnode-2-27: FR3 Build 298 triggered by scotch
gnode-2-30: FR3 Build 298 triggered by scotch
gnode-2-31: FR3 Build 298 triggered by scotch
gnode-2-32: FR3 Build 298 triggered by scotch
gnode-2-33: FR3 Build 298 triggered by scotch
