### ISSUE TITLE
Poster layout

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE-ACAT-2017#5]
@bazinski Once  you've added the file for the poster (I'm guessing in LaTex, but waiting for #2 for details), let's discuss the initial layout and so on here. Once it's more or less in progress, we'll move it to Discourse.

What should we have in the poster ? 

- [ ] Summary of the architecture and technology ? 
- [ ] Schematic diagram of  how CODE-RADE works ? Workflow, actors, etc.
- [ ] Schematic diagram of the delivery mechanism ?
- [ ] map of where it can be executed  (grid sites, etc)
- [ ] description of repos and repo layouts  ? 
- [ ] TODO and next features ?

**Comment by bazinski** [comment]
@brucellino The above are tickboxes am I supposed to do something with them ?
i take it docker/quay.io go in first point.
I think maybe a section clearly showing the lifting of the burden on scientists.  I have not thought how to make this completely clear, maybe before and after workflow described in point 2 ?

**Comment by brucellino** [comment]
The tick boxes are sub-points. If we've discussed them, they get ticked off. 

> I think maybe a section clearly showing the lifting of the burden on scientists.

The burden is is on the sysadmins at the sites. The section should say how it's easy for users to propose and deliver their own applications in the absence of action on the part of the sysadmins. Automation and transparent testing allows this.

**Comment by bazinski** [comment]
I have to disagree with the last part, its a huge burden lifted for a scientist to get their stuff into a ci system and auto deployed with out having to contact sites, sit and compile stuff yourself etc.
I am talking with reference to what happens on our system, not mine.

**Comment by bazinski** [comment]
@brucellino i forgot the identifier of your name in the above update
